id: 86e9949d124a4207a8548470e8a4ed24
title: Toh_196-The_Dwelling_Place_of_Manjusri-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-016
  eft-text-version: 1.1.5 2020
